import type { Metadata } from "next";
import { Geist, Geist_Mono, Poppins } from "next/font/google";
import Script from "next/script";

import "bootstrap/dist/css/bootstrap.min.css";
import "bootstrap-icons/font/bootstrap-icons.css";
import "aos/dist/aos.css";
import "@fancyapps/ui/dist/fancybox/fancybox.css";
import "@fortawesome/fontawesome-free/css/all.min.css";
import "swiper/css";

import "./globals.css";

import AOSProvider from "@/components/providers/AOSProvider";
import LayoutWrapper from "@/components/layout/layoutWrapper/layoutWrapper";
import { ReduxProvider } from "@/redux/providers/ReduxProvider";
import { Toaster } from "sonner";
import Providers from "@/redux/provider/providers";

/* ================= FONTS ================= */

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

const poppins = Poppins({
  subsets: ["latin"],
  weight: ["300", "400", "500", "600", "700"],
  variable: "--font-poppins",
});

/* ================= METADATA ================= */

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

/* ================= ROOT LAYOUT ================= */

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body
        className={`${poppins.variable} ${geistSans.variable} ${geistMono.variable} antialiased`}
        style={{ fontFamily: "var(--font-poppins)" }}
      >
        {/* Redux Global Provider */}{" "}
        <ReduxProvider>
          {/* Animation Provider */} <AOSProvider />
          {/* Global Toasts */}
          <Toaster richColors position="top-center" duration={3000} />
          {/* Layout Wrapper */}
          <Providers> <LayoutWrapper>{children}</LayoutWrapper></Providers>
         
        </ReduxProvider>
        {/* Bootstrap JS */}
        <Script
          src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.8/dist/js/bootstrap.bundle.min.js"
          strategy="afterInteractive"
        />
      </body>
    </html>
  );
}

// import type { Metadata } from "next";
// import { Geist, Geist_Mono } from "next/font/google";

// import "bootstrap/dist/css/bootstrap.min.css";
// import "bootstrap-icons/font/bootstrap-icons.css";
// import "aos/dist/aos.css";
// import "@fancyapps/ui/dist/fancybox/fancybox.css";
// import AOSProvider from "@/components/providers/AOSProvider";
// import Script from "next/script";
// import { poppins } from "./fonts/poppins";
// import "@fortawesome/fontawesome-free/css/all.min.css";

// import "./globals.css";
// import { ReduxProvider } from "@/redux/providers/ReduxProvider";

// const geistSans = Geist({
//   variable: "--font-geist-sans",
//   subsets: ["latin"],
// });

// const geistMono = Geist_Mono({
//   variable: "--font-geist-mono",
//   subsets: ["latin"],
// });

// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

// export default function RootLayout({
//   children,
// }: Readonly<{
//   children: React.ReactNode;
// }>) {
//   return (
//     <html lang="en">
//       <body
//         className={`${poppins.variable} antialiased`}
//         style={{ fontFamily: "var(--font-poppins)" }}
//       >
//       {/* AOS initializer */}
//         <AOSProvider/>

//        <ReduxProvider>
//           {children}
//         </ReduxProvider>

//         {/* Bootstrap JS */}
//         <Script
//           src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.8/dist/js/bootstrap.bundle.min.js"
//           strategy="afterInteractive"
//         />
//       </body>
//     </html>
//   );
// }
